"""update user blog tables

Revision ID: d0fb7a3d3ae3
Revises:
Create Date: 2023-08-19 12:50:40.154679

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "d0fb7a3d3ae3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("blog", "author_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("blog", "author_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
